import type { Metadata } from "next";
import { Buda } from "next/font/google";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Navbar2 } from "./UI/Navbar2";
import { Footer7 } from "./UI/Footer7";

// Heading: Mohave
const headingFont = Buda({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "300",
});

// Body: Nunito Sans
const bodyFont = Raleway({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], // säädä tarpeen mukaan
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${headingFont.variable} ${bodyFont.variable} antialiased`}
      >
        <Navbar2 />
        {children}
        <Footer7 />
      </body>
    </html>
  );
}
